# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: practicetest123
# "service" is the name of this project. This will also be added to your AWS resource names.
service: categoryService

provider:
  name: aws
  runtime: nodejs22.x
  region: ap-southeast-1
  environment:
    CATEGORY_TABLE: Categories
    CATEGORY_IMAGES_BUCKET: category-bucket-sls
    REGION: ap-southeast-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:PutObject
        - dynamodb:PutItem
        - dynamodb:UpdateItem
      Resource:
        - !Sub arn:aws:s3:::${self:provider.environment.CATEGORY_IMAGES_BUCKET}/*
        - !Sub arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${self:provider.environment.CATEGORY_TABLE}

resources:
  Resources:
    CategoryImagesBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: category-bucket-sls
        PublicAccessBlockConfiguration:
          BlockPublicAcls: false
          IgnorePublicAcls: false
          BlockPublicPolicy: false
          RestrictPublicBuckets: false
        CorsConfiguration:
          CorsRules:
            - AllowedHeaders:
                - '*'
              AllowedMethods:
                - PUT
              AllowedOrigins:
                - '*'
    CategoryImagesBucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket: !Ref CategoryImagesBucket
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Principal: '*'
              Action:
                - s3:PutObject
                - s3:GetObject
              # This is join method to concatenate the bucket ARN with '/*' to allow access to all objects in the bucket
              # There could be multiple ways to write !Join method some of them are:
              # 1. !Join [ '', [!GetAtt CategoryImagesBucket.Arn, '/*'] ]
              # 2. !Join [ '', ['arn:aws:s3:::', !Ref CategoryImagesBucket, '/*'] ]
              Resource: !Join ['', [!GetAtt CategoryImagesBucket.Arn, '/*']]

    CategoryTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Categories
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: fileName
            AttributeType: S
        KeySchema:
          - AttributeName: fileName
            KeyType: HASH

functions:
  getUploadUrl:
    handler: handlers/getUploadUrl.getUploadUrl
    events:
      - httpApi:
          path: /upload-url
          method: post
  updateCategoryData:
    handler: handlers/updateCategoryData.updateCategoryData
    events:
      - s3:
          bucket: !Ref CategoryImagesBucket
          event: s3:ObjectCreated:Put
          existing: true # This allows the function to be triggered by an existing object in the bucket
