# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: practicetest123
# "service" is the name of this project. This will also be added to your AWS resource names.
service: categoryService

provider:
  name: aws
  runtime: nodejs22.x
  region: ap-southeast-1
  environment:
    CATEGORY_TABLE: Categories
    CATEGORY_IMAGES_BUCKET: category-images-bucket-sls
    REGION: ap-southeast-1

resources:
  Resources:
    CategoryImagesBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: category-images-bucket-sls

    CategoryTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Categories
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: categoryName
            AttributeType: S
        KeySchema:
          - AttributeName: categoryName
            KeyType: HASH

functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /
          method: get
